PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE Zettel( Symbol text,Klasse text, Beschreibung text);
INSERT INTO "Zettel" VALUES(':/Gefahrenklasse/1.svg','1','Explosiv');
INSERT INTO "Zettel" VALUES(':/Gefahrenklasse/2.1.svg','2.1','Gas (entzündbar)');
INSERT INTO "Zettel" VALUES(':/Gefahrenklasse/2.2.svg','2.2','Gas (nicht entzündbar)');
INSERT INTO "Zettel" VALUES(':/Gefahrenklasse/2.3.svg','2.3','Gas (giftig)');
INSERT INTO "Zettel" VALUES(':/Gefahrenklasse/3.svg','3','flüssige Stoffe (entzündbar)');
INSERT INTO "Zettel" VALUES(':/Gefahrenklasse/4.1.svg','4.1','feste Stoffe (entzündbar)');
INSERT INTO "Zettel" VALUES(':/Gefahrenklasse/4.2.svg','4.2','selbstentzündlche Stoffe');
INSERT INTO "Zettel" VALUES(':/Gefahrenklasse/4.3.svg','4.3','bildet mit Wasser entzündliche Gase');
INSERT INTO "Zettel" VALUES(':/Gefahrenklasse/5.1.svg','5.1','brandfördernt');
INSERT INTO "Zettel" VALUES(':/Gefahrenklasse/5.2.svg','5.2','organische Peroxide');
INSERT INTO "Zettel" VALUES(':/Gefahrenklasse/6.1.svg','6.1','giftig');
INSERT INTO "Zettel" VALUES(':/Gefahrenklasse/6.2.svg','6.2','biologisch anteckend');
INSERT INTO "Zettel" VALUES(':/Gefahrenklasse/7A.svg','7A','radioaktive Strahlung <= 0,005 mSv/h');
INSERT INTO "Zettel" VALUES(':/Gefahrenklasse/7B.svg','7B','radioaktive Strahlung > 0,005 <= 0,5 mSv/h');
INSERT INTO "Zettel" VALUES(':/Gefahrenklasse/7C.svg','7C','radioaktive Strahlung > 0,5 <= 2 mSv/h');
INSERT INTO "Zettel" VALUES(':/Gefahrenklasse/7E.svg','7E','radioaktive Strahlung > 2 <= 10 mSv/h');
INSERT INTO "Zettel" VALUES(':/Gefahrenklasse/8.svg','8','ätzend');
INSERT INTO "Zettel" VALUES(':/Gefahrenklasse/9.svg','9','verschiedenes');
INSERT INTO "Zettel" VALUES(':/Gefahrenklasse/Umwelt.svg','','Umweltgefährdend');
INSERT INTO "Zettel" VALUES(':/Gefahrenklasse/Heiß.svg','','Heiß Flüssigkeite => 100 °C, Feststoffe > 240 °C');
COMMIT;
