#! /bin/bash
Datei="Gefahrenzettel.dat"
rm -f $Datei 2>/dev/null
sqlite3 $Datei "create table Zettel( Symbol text,Klasse text, Beschreibung text,ID text unique);"
sqlite3 $Datei "insert into Zettel Values(':/Gefahrenklasse/1.svg','1','Explosiv','0');"
sqlite3 $Datei "insert into Zettel Values(':/Gefahrenklasse/2.1.svg','2.1','Gas (entzündbar)','1');"
sqlite3 $Datei "insert into Zettel Values(':/Gefahrenklasse/2.2.svg','2.2','Gas (nicht entzündbar)','2');"
sqlite3 $Datei "insert into Zettel Values(':/Gefahrenklasse/2.3.svg','2.3','Gas (giftig)','3');"
sqlite3 $Datei "insert into Zettel Values(':/Gefahrenklasse/3.svg','3','flüssige Stoffe (entzündbar)','4');"
sqlite3 $Datei "insert into Zettel Values(':/Gefahrenklasse/4.1.svg','4.1','feste Stoffe (entzündbar)','5');"
sqlite3 $Datei "insert into Zettel Values(':/Gefahrenklasse/4.2.svg','4.2','selbstentzündlche Stoffe','6');"
sqlite3 $Datei "insert into Zettel Values(':/Gefahrenklasse/4.3.svg','4.3','bildet mit Wasser entzündlcihe Gase','7');"
sqlite3 $Datei "insert into Zettel Values(':/Gefahrenklasse/5.1.svg','5.1','brandfördernt','8');"
sqlite3 $Datei "insert into Zettel Values(':/Gefahrenklasse/5.2.svg','5.2','organische Peroxide','9');"
sqlite3 $Datei "insert into Zettel Values(':/Gefahrenklasse/6.1.svg','6.1','giftig','10');"
sqlite3 $Datei "insert into Zettel Values(':/Gefahrenklasse/6.2.svg','6.2','biologisch anteckend','11');"
sqlite3 $Datei "insert into Zettel Values(':/Gefahrenklasse/7A.svg','7A','radioaktive Strahlung <= 0,005 mSv/h','12');"
sqlite3 $Datei "insert into Zettel Values(':/Gefahrenklasse/7B.svg','7B','radioaktive Strahlung > 0,005 <= 0,5 mSv/h','13');"
sqlite3 $Datei "insert into Zettel Values(':/Gefahrenklasse/7C.svg','7C','radioaktive Strahlung > 0,5 <= 2 mSv/h','14');"
sqlite3 $Datei "insert into Zettel Values(':/Gefahrenklasse/7E.svg','7E','radioaktive Strahlung > 2 <= 10 mSv/h','15');"
sqlite3 $Datei "insert into Zettel Values(':/Gefahrenklasse/8.svg','8','ätzend','16');"
sqlite3 $Datei "insert into Zettel Values(':/Gefahrenklasse/9.svg','9','verschiedenes','17');"
sqlite3 $Datei "insert into Zettel Values(':/Gefahrenklasse/Umwelt.svg','','Umweltgefährdend','18');"
sqlite3 $Datei "insert into Zettel Values(':/Gefahrenklasse/Heiß.svg','','Heiß Flüssigkeite => 100 °C, Feststoffe > 240 °C','19');"
