#! /bin/bash
Datei=Gefahrgutnummern.dat
rm -f $Datei 2>/dev/null
sqlite3 $Datei "create table Gefahrgutnummern(Nummer text,Beschreibung text);"
#Gas
sqlite3 $Datei "insert into Gefahrgutnummern Values('20','reaktionsträges Gas');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('22','tiefgekühltes Gas');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('223','tiefgekühltes brennbares Gas');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('225','tiefgekühltes brandförderndes Gas');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('23','brennbares Gas');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('236','brennbares Gas, giftig');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('239','brennbares Gas, das spontan zu heftiger Reaktion führen kann');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('25','brandförderndes Gas');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('26','giftiges Gas');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('265','giftiges Gas, brandfördernd');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('266','sehr giftiges Gas');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('268','giftiges Gas, ätzend');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('286','ätzendes Gas, giftig');"
#Flüssig
sqlite3 $Datei "insert into Gefahrgutnummern Values('30','entzündbarer flüssiger Stoff (Flammpunkt von 23 °C bis einschl. 61 °C) oder entzündbarer flüssiger Stoff oder fester Stoff in geschmolzenem Zustand mit Flammpunkt über 61 °C, auf oder über seinen Flammpunkt erwärmt oder selbsterhitzungsfähiger flüssiger Stoff');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('323','entzündbarer flüssiger Stoff, der mit Wasser reagiert und entzündbare Gase bildet');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('X323','entzündbarer flüssiger Stoff, der mit Wasser gefährlich reagiert und entzündbare Gase bildet (Wasser darf nur im Einverständnis mit Sachverständigem verwendet werden)');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('33','leicht entzündbarer flüssiger Stoff (Flammpunkt unter 23 °C)');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('X33','leicht entzündbarer flüssiger Stoff (Flammpunkt unter 23 °C) (Wasser darf nur im Einverständnis mit Sachverständigem verwendet werden)');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('333','selbstentzündlicher (pyrophorer) flüssiger Stoff');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('X333','selbstentzündlicher (pyrophorer) flüssiger Stoff, der mit Wasser gefährlich reagiert (Wasser darf nur im Einverständnis mit Sachverständigem verwendet werden)');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('336','leicht entzündbarer flüssiger Stoff, giftig');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('338','leicht entzündbarer flüssiger Stoff, ätzend');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('X338','leicht entzündbarer flüssiger Stoff, ätzend, der mit Wasser gefährlich reagiert (Wasser darf nur im Einverständnis mit Sachverständigem verwendet werden)');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('339','leicht entzündbarer flüssiger Stoff, der spontan zu heftiger Reaktion führen kann');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('36','entzündbarer flüssiger Stoff (Flammpunkt von 23 °C bis einschl. 61 °C), schwach giftig, oder selbsterhitzungsfähiger flüssiger Stoff, giftig');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('362','entzündbarer flüssiger Stoff, giftig, der mit Wasser reagiert und entzündbare Gase bildet (Wasser darf nur im Einverständnis mit Sachverständigem verwendet werden)');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('X362','entzündbarer flüssiger Stoff, giftig, der mit Wasser gefährlich reagiert und entzündbare Gase bildet (Wasser darf nur im Einverständnis mit Sachverständigem verwendet werden)');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('38','entzündbarer flüssiger Stoff (Flammpunkt von 23 °C bis einschl. 61 °C), schwach ätzend, oder selbsterhitzungsfähiger flüssiger Stoff, ätzend');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('382','entzündbarer flüssiger Stoff, ätzend, der mit Wasser reagiert und entzündbare Gase bildet (Wasser darf nur im Einverständnis mit Sachverständigem verwendet werden)');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('X382','entzündbarer flüssiger Stoff, ätzend, der mit Wasser gefährlich reagiert und entzündbare Gase bildet (Wasser darf nur im Einverständnis mit Sachverständigem verwendet werden)');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('39','entzündbarer flüssiger Stoff, der spontan zu heftiger Reaktion führen kann');"
#Feste
sqlite3 $Datei "insert into Gefahrgutnummern Values('40','entzündbarer oder selbsterhitzungsfähiger fester Stoff');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('423','fester Stoff, der mit Wasser reagiert und entzündbare Gase bildet');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('X423','entzündbarer fester Stoff, der mit Wasser gefährlich reagiert und entzündbare Gase bildet (Wasser darf nur im Einverständnis mit Sachverständigen verwendet werden)');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('44','entzündbarer fester Stoff, der sich bei erhöhter Temperatur in geschmolzenem Zustand befindet');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('446','entzündbarer fester Stoff, giftig, der sich bei erhöhter Temperatur in geschmolzenem Zustand befindet');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('46','entzündbarer oder selbsterhitzungfähiger fester Stoff, giftig');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('462','fester Stoff, giftig, der mit Wasser reagiert und entzündbare Gase bildet');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('48','entzündbarer oder selbsterhitzungsfähiger fester Stoff, ätzend');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('482','fester Stoff, ätzend, der mit Wasser reagiert und entzündbare Gase bildet');"
#oxidierende Stoffe
sqlite3 $Datei "insert into Gefahrgutnummern Values('50','brandfördernder Stoff');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('539','entzündbares organisches Peroxid');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('55','stark brandfördernder Stoff');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('556','stark brandfördernder Stoff, giftig');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('558','stark brandfördernder Stoff, ätzend');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('559','stark brandfördernder Stoff, der spontan zu heftiger Reaktion führen kann');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('56','brandfördernder Stoff, giftig');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('568','brandfördernder Stoff, giftig, ätzend');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('58','brandfördernder Stoff, ätzend');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('59','brandfördernder Stoff, der spontan zu heftiger Reaktion führen kann');"
#Giftig
sqlite3 $Datei "insert into Gefahrgutnummern Values('60','giftiger oder schwach giftiger Stoff');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('606','ansteckungsgefährlicher Stoff');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('623','giftiger flüssiger Stoff, der mit Wasser reagiert und entzündbare Gase bildet');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('63','giftiger Stoff, entzündbar (Flammpunkt von 23 °C bis 61 °C)');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('638','giftiger Stoff, entzündbar (Flammpunkt von 23 °C bis 61 °C), ätzend');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('638','giftiger Stoff, entzündbar (Flammpunkt von 23 °C bis 61 °C), der spontan zu heftiger Reaktion führen kann');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('64','giftiger fester Stoff, entzündbar oder selbsterhitzungsfähig');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('642','giftiger fester Stoff, der mit Wasser reagiert und entzündbare Gase bildet');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('65','giftiger Stoff, brandfördernd');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('66','sehr giftiger Stoff');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('663','sehr giftiger Stoff, entzündbar (Flammpunkt nicht über 61 °C)');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('664','sehr giftiger fester Stoff, entzündbar oder selbsterhitzungsfähig');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('665','sehr giftiger Stoff, brandfördernd');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('668','sehr giftiger Stoff, ätzend');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('669','sehr giftiger Stoff, der spontan zu heftiger Reaktion führen kann');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('68','giftiger Stoff, ätzend');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('69','giftiger oder schwach giftiger Stoff, der spontan zu heftiger Reaktion führen kann');"
#Radioaktiv
sqlite3 $Datei "insert into Gefahrgutnummern Values('70','radioaktiver Stoff');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('71','radioaktives Gas');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('723','radioaktives Gas, brennbar');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('73','radioaktiver Stoff, entzündbar (Flammpunkt nicht über 61 °C)');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('74','radioaktiver fester Stoff, entzündbar');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('75','radioaktiver Stoff, brandfördernd');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('76','radioaktiver Stoff, giftig');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('78','radioaktiver Stoff, ätzend');"
#Ätzend
sqlite3 $Datei "insert into Gefahrgutnummern Values('80','ätzender oder schwach ätzender Stoff');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('X80','ätzender oder schwach ätzender Stoff, der mit Wasser gefährlich reagiert (Wasser darf nur im Einvernehmen mit Sachverständigen verwendet werden)');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('823','ätzender flüssiger Stoff, der mit Wasser reagiert und entzündbare Gase bildet');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('83','ätzender oder schwach ätzender Stoff, entzündbar (Flammpunkt von 23 °C bis 61 °C)');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('X83','ätzender oder schwach ätzender Stoff, entzündbar (Flammpunkt von 23 °C bis 61 °C), der mit Wasser gefährlich reagiert (Wasser darf nur mit Einverständnis eines Sachverständigen verwendet werden)');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('836','ätzender oder schwach ätzender Stoff, entzündbar (Flammpunkt von 23 °C bis 61 °C), giftig');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('839','ätzender oder schwach ätzender Stoff, entzündbar (Flammpunkt von 23 °C bis 61 °C), der spontan zu heftiger Reaktion führen kann');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('X839','ätzender oder schwach ätzender Stoff, entzündbar (Flammpunkt von 23 °C bis 61 °C), der spontan zu heftiger Reaktion führen kann und mit Wasser gefährlich reagiert (Wasser darf nur im Einvernehmen mit Sachverständigen verwendet werden)');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('84','ätzender fester Stoff, entzündbar oder selbsterhitzungsfähig');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('842','ätzender fester Stoff, der mit Wasser reagiert und entzündbare Gase bildet');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('85','ätzender oder schwach ätzender Stoff, brandfördernd');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('856','ätzender oder schwach ätzender Stoff, brandfördernd und giftig');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('86','ätzender oder schwach ätzender Stoff, giftig');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('88','stark ätzender Stoff');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('X88','stark ätzender Stoff, der mit Wasser gefährlich reagiert (Wasser darf nur im Einvernehmen mit Sachverständigen verwendet werden)');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('883','stark ätzender Stoff, entzündbar (Flammpunkt von 23 °C bis 61 °C)');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('884','stark ätzender fester Stoff, entzündbar oder selbsterhitzungsfähig');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('885','stark ätzender Stoff, brandfördernd');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('886','stark ätzender Stoff, giftig');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('X886','stark ätzender Stoff, giftig, der mit Wasser gefährlich reagiert (Wasser darf nur im Einvernehmen mit Sachverständigen verwendet werden)');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('89','ätzender oder schwach ätzender Stoff, der spontan zu heftiger Reaktion führen kann');"
#Sonstiges
sqlite3 $Datei "insert into Gefahrgutnummern Values('90','umweltgefährdender Stoff oder verschiedene gefährliche Stoffe');"
sqlite3 $Datei "insert into Gefahrgutnummern Values('99','verschiedene gefährliche Stoffe in erwärmtem Zustand');"
