PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE Gefahrgutnummern(Nummer text,Beschreibung text);
INSERT INTO "Gefahrgutnummern" VALUES('20','reaktionsträges Gas');
INSERT INTO "Gefahrgutnummern" VALUES('22','tiefgekühltes Gas');
INSERT INTO "Gefahrgutnummern" VALUES('223','tiefgekühltes brennbares Gas');
INSERT INTO "Gefahrgutnummern" VALUES('225','tiefgekühltes brandförderndes Gas');
INSERT INTO "Gefahrgutnummern" VALUES('23','brennbares Gas');
INSERT INTO "Gefahrgutnummern" VALUES('236','brennbares Gas, giftig');
INSERT INTO "Gefahrgutnummern" VALUES('239','brennbares Gas, das spontan zu heftiger Reaktion führen kann');
INSERT INTO "Gefahrgutnummern" VALUES('25','brandförderndes Gas');
INSERT INTO "Gefahrgutnummern" VALUES('26','giftiges Gas');
INSERT INTO "Gefahrgutnummern" VALUES('265','giftiges Gas, brandfördernd');
INSERT INTO "Gefahrgutnummern" VALUES('266','sehr giftiges Gas');
INSERT INTO "Gefahrgutnummern" VALUES('268','giftiges Gas, ätzend');
INSERT INTO "Gefahrgutnummern" VALUES('286','ätzendes Gas, giftig');
INSERT INTO "Gefahrgutnummern" VALUES('30','entzündbarer flüssiger Stoff (Flammpunkt von 23 °C bis einschl. 61 °C) oder entzündbarer flüssiger Stoff oder fester Stoff in geschmolzenem Zustand mit Flammpunkt über 61 °C, auf oder über seinen Flammpunkt erwärmt oder selbsterhitzungsfähiger flüssiger Stoff');
INSERT INTO "Gefahrgutnummern" VALUES('323','entzündbarer flüssiger Stoff, der mit Wasser reagiert und entzündbare Gase bildet');
INSERT INTO "Gefahrgutnummern" VALUES('X323','entzündbarer flüssiger Stoff, der mit Wasser gefährlich reagiert und entzündbare Gase bildet (Wasser darf nur im Einverständnis mit Sachverständigem verwendet werden)');
INSERT INTO "Gefahrgutnummern" VALUES('33','leicht entzündbarer flüssiger Stoff (Flammpunkt unter 23 °C)');
INSERT INTO "Gefahrgutnummern" VALUES('X33','leicht entzündbarer flüssiger Stoff (Flammpunkt unter 23 °C) (Wasser darf nur im Einverständnis mit Sachverständigem verwendet werden)');
INSERT INTO "Gefahrgutnummern" VALUES('333','selbstentzündlicher (pyrophorer) flüssiger Stoff');
INSERT INTO "Gefahrgutnummern" VALUES('X333','selbstentzündlicher (pyrophorer) flüssiger Stoff, der mit Wasser gefährlich reagiert (Wasser darf nur im Einverständnis mit Sachverständigem verwendet werden)');
INSERT INTO "Gefahrgutnummern" VALUES('336','leicht entzündbarer flüssiger Stoff, giftig');
INSERT INTO "Gefahrgutnummern" VALUES('338','leicht entzündbarer flüssiger Stoff, ätzend');
INSERT INTO "Gefahrgutnummern" VALUES('X338','leicht entzündbarer flüssiger Stoff, ätzend, der mit Wasser gefährlich reagiert (Wasser darf nur im Einverständnis mit Sachverständigem verwendet werden)');
INSERT INTO "Gefahrgutnummern" VALUES('339','leicht entzündbarer flüssiger Stoff, der spontan zu heftiger Reaktion führen kann');
INSERT INTO "Gefahrgutnummern" VALUES('36','entzündbarer flüssiger Stoff (Flammpunkt von 23 °C bis einschl. 61 °C), schwach giftig, oder selbsterhitzungsfähiger flüssiger Stoff, giftig');
INSERT INTO "Gefahrgutnummern" VALUES('362','entzündbarer flüssiger Stoff, giftig, der mit Wasser reagiert und entzündbare Gase bildet (Wasser darf nur im Einverständnis mit Sachverständigem verwendet werden)');
INSERT INTO "Gefahrgutnummern" VALUES('X362','entzündbarer flüssiger Stoff, giftig, der mit Wasser gefährlich reagiert und entzündbare Gase bildet (Wasser darf nur im Einverständnis mit Sachverständigem verwendet werden)');
INSERT INTO "Gefahrgutnummern" VALUES('38','entzündbarer flüssiger Stoff (Flammpunkt von 23 °C bis einschl. 61 °C), schwach ätzend, oder selbsterhitzungsfähiger flüssiger Stoff, ätzend');
INSERT INTO "Gefahrgutnummern" VALUES('382','entzündbarer flüssiger Stoff, ätzend, der mit Wasser reagiert und entzündbare Gase bildet (Wasser darf nur im Einverständnis mit Sachverständigem verwendet werden)');
INSERT INTO "Gefahrgutnummern" VALUES('X382','entzündbarer flüssiger Stoff, ätzend, der mit Wasser gefährlich reagiert und entzündbare Gase bildet (Wasser darf nur im Einverständnis mit Sachverständigem verwendet werden)');
INSERT INTO "Gefahrgutnummern" VALUES('39','entzündbarer flüssiger Stoff, der spontan zu heftiger Reaktion führen kann');
INSERT INTO "Gefahrgutnummern" VALUES('40','entzündbarer oder selbsterhitzungsfähiger fester Stoff');
INSERT INTO "Gefahrgutnummern" VALUES('423','fester Stoff, der mit Wasser reagiert und entzündbare Gase bildet');
INSERT INTO "Gefahrgutnummern" VALUES('X423','entzündbarer fester Stoff, der mit Wasser gefährlich reagiert und entzündbare Gase bildet (Wasser darf nur im Einverständnis mit Sachverständigen verwendet werden)');
INSERT INTO "Gefahrgutnummern" VALUES('44','entzündbarer fester Stoff, der sich bei erhöhter Temperatur in geschmolzenem Zustand befindet');
INSERT INTO "Gefahrgutnummern" VALUES('446','entzündbarer fester Stoff, giftig, der sich bei erhöhter Temperatur in geschmolzenem Zustand befindet');
INSERT INTO "Gefahrgutnummern" VALUES('46','entzündbarer oder selbsterhitzungfähiger fester Stoff, giftig');
INSERT INTO "Gefahrgutnummern" VALUES('462','fester Stoff, giftig, der mit Wasser reagiert und entzündbare Gase bildet');
INSERT INTO "Gefahrgutnummern" VALUES('48','entzündbarer oder selbsterhitzungsfähiger fester Stoff, ätzend');
INSERT INTO "Gefahrgutnummern" VALUES('482','fester Stoff, ätzend, der mit Wasser reagiert und entzündbare Gase bildet');
INSERT INTO "Gefahrgutnummern" VALUES('50','brandfördernder Stoff');
INSERT INTO "Gefahrgutnummern" VALUES('539','entzündbares organisches Peroxid');
INSERT INTO "Gefahrgutnummern" VALUES('55','stark brandfördernder Stoff');
INSERT INTO "Gefahrgutnummern" VALUES('556','stark brandfördernder Stoff, giftig');
INSERT INTO "Gefahrgutnummern" VALUES('558','stark brandfördernder Stoff, ätzend');
INSERT INTO "Gefahrgutnummern" VALUES('559','stark brandfördernder Stoff, der spontan zu heftiger Reaktion führen kann');
INSERT INTO "Gefahrgutnummern" VALUES('56','brandfördernder Stoff, giftig');
INSERT INTO "Gefahrgutnummern" VALUES('568','brandfördernder Stoff, giftig, ätzend');
INSERT INTO "Gefahrgutnummern" VALUES('58','brandfördernder Stoff, ätzend');
INSERT INTO "Gefahrgutnummern" VALUES('59','brandfördernder Stoff, der spontan zu heftiger Reaktion führen kann');
INSERT INTO "Gefahrgutnummern" VALUES('60','giftiger oder schwach giftiger Stoff');
INSERT INTO "Gefahrgutnummern" VALUES('606','ansteckungsgefährlicher Stoff');
INSERT INTO "Gefahrgutnummern" VALUES('623','giftiger flüssiger Stoff, der mit Wasser reagiert und entzündbare Gase bildet');
INSERT INTO "Gefahrgutnummern" VALUES('63','giftiger Stoff, entzündbar (Flammpunkt von 23 °C bis 61 °C)');
INSERT INTO "Gefahrgutnummern" VALUES('638','giftiger Stoff, entzündbar (Flammpunkt von 23 °C bis 61 °C), ätzend');
INSERT INTO "Gefahrgutnummern" VALUES('638','giftiger Stoff, entzündbar (Flammpunkt von 23 °C bis 61 °C), der spontan zu heftiger Reaktion führen kann');
INSERT INTO "Gefahrgutnummern" VALUES('64','giftiger fester Stoff, entzündbar oder selbsterhitzungsfähig');
INSERT INTO "Gefahrgutnummern" VALUES('642','giftiger fester Stoff, der mit Wasser reagiert und entzündbare Gase bildet');
INSERT INTO "Gefahrgutnummern" VALUES('65','giftiger Stoff, brandfördernd');
INSERT INTO "Gefahrgutnummern" VALUES('66','sehr giftiger Stoff');
INSERT INTO "Gefahrgutnummern" VALUES('663','sehr giftiger Stoff, entzündbar (Flammpunkt nicht über 61 °C)');
INSERT INTO "Gefahrgutnummern" VALUES('664','sehr giftiger fester Stoff, entzündbar oder selbsterhitzungsfähig');
INSERT INTO "Gefahrgutnummern" VALUES('665','sehr giftiger Stoff, brandfördernd');
INSERT INTO "Gefahrgutnummern" VALUES('668','sehr giftiger Stoff, ätzend');
INSERT INTO "Gefahrgutnummern" VALUES('669','sehr giftiger Stoff, der spontan zu heftiger Reaktion führen kann');
INSERT INTO "Gefahrgutnummern" VALUES('68','giftiger Stoff, ätzend');
INSERT INTO "Gefahrgutnummern" VALUES('69','giftiger oder schwach giftiger Stoff, der spontan zu heftiger Reaktion führen kann');
INSERT INTO "Gefahrgutnummern" VALUES('70','radioaktiver Stoff');
INSERT INTO "Gefahrgutnummern" VALUES('71','radioaktives Gas');
INSERT INTO "Gefahrgutnummern" VALUES('723','radioaktives Gas, brennbar');
INSERT INTO "Gefahrgutnummern" VALUES('73','radioaktiver Stoff, entzündbar (Flammpunkt nicht über 61 °C)');
INSERT INTO "Gefahrgutnummern" VALUES('74','radioaktiver fester Stoff, entzündbar');
INSERT INTO "Gefahrgutnummern" VALUES('75','radioaktiver Stoff, brandfördernd');
INSERT INTO "Gefahrgutnummern" VALUES('76','radioaktiver Stoff, giftig');
INSERT INTO "Gefahrgutnummern" VALUES('78','radioaktiver Stoff, ätzend');
INSERT INTO "Gefahrgutnummern" VALUES('80','ätzender oder schwach ätzender Stoff');
INSERT INTO "Gefahrgutnummern" VALUES('X80','ätzender oder schwach ätzender Stoff, der mit Wasser gefährlich reagiert (Wasser darf nur im Einvernehmen mit Sachverständigen verwendet werden)');
INSERT INTO "Gefahrgutnummern" VALUES('823','ätzender flüssiger Stoff, der mit Wasser reagiert und entzündbare Gase bildet');
INSERT INTO "Gefahrgutnummern" VALUES('83','ätzender oder schwach ätzender Stoff, entzündbar (Flammpunkt von 23 °C bis 61 °C)');
INSERT INTO "Gefahrgutnummern" VALUES('X83','ätzender oder schwach ätzender Stoff, entzündbar (Flammpunkt von 23 °C bis 61 °C), der mit Wasser gefährlich reagiert (Wasser darf nur mit Einverständnis eines Sachverständigen verwendet werden)');
INSERT INTO "Gefahrgutnummern" VALUES('836','ätzender oder schwach ätzender Stoff, entzündbar (Flammpunkt von 23 °C bis 61 °C), giftig');
INSERT INTO "Gefahrgutnummern" VALUES('839','ätzender oder schwach ätzender Stoff, entzündbar (Flammpunkt von 23 °C bis 61 °C), der spontan zu heftiger Reaktion führen kann');
INSERT INTO "Gefahrgutnummern" VALUES('X839','ätzender oder schwach ätzender Stoff, entzündbar (Flammpunkt von 23 °C bis 61 °C), der spontan zu heftiger Reaktion führen kann und mit Wasser gefährlich reagiert (Wasser darf nur im Einvernehmen mit Sachverständigen verwendet werden)');
INSERT INTO "Gefahrgutnummern" VALUES('84','ätzender fester Stoff, entzündbar oder selbsterhitzungsfähig');
INSERT INTO "Gefahrgutnummern" VALUES('842','ätzender fester Stoff, der mit Wasser reagiert und entzündbare Gase bildet');
INSERT INTO "Gefahrgutnummern" VALUES('85','ätzender oder schwach ätzender Stoff, brandfördernd');
INSERT INTO "Gefahrgutnummern" VALUES('856','ätzender oder schwach ätzender Stoff, brandfördernd und giftig');
INSERT INTO "Gefahrgutnummern" VALUES('86','ätzender oder schwach ätzender Stoff, giftig');
INSERT INTO "Gefahrgutnummern" VALUES('88','stark ätzender Stoff');
INSERT INTO "Gefahrgutnummern" VALUES('X88','stark ätzender Stoff, der mit Wasser gefährlich reagiert (Wasser darf nur im Einvernehmen mit Sachverständigen verwendet werden)');
INSERT INTO "Gefahrgutnummern" VALUES('883','stark ätzender Stoff, entzündbar (Flammpunkt von 23 °C bis 61 °C)');
INSERT INTO "Gefahrgutnummern" VALUES('884','stark ätzender fester Stoff, entzündbar oder selbsterhitzungsfähig');
INSERT INTO "Gefahrgutnummern" VALUES('885','stark ätzender Stoff, brandfördernd');
INSERT INTO "Gefahrgutnummern" VALUES('886','stark ätzender Stoff, giftig');
INSERT INTO "Gefahrgutnummern" VALUES('X886','stark ätzender Stoff, giftig, der mit Wasser gefährlich reagiert (Wasser darf nur im Einvernehmen mit Sachverständigen verwendet werden)');
INSERT INTO "Gefahrgutnummern" VALUES('89','ätzender oder schwach ätzender Stoff, der spontan zu heftiger Reaktion führen kann');
INSERT INTO "Gefahrgutnummern" VALUES('90','umweltgefährdender Stoff oder verschiedene gefährliche Stoffe');
INSERT INTO "Gefahrgutnummern" VALUES('99','verschiedene gefährliche Stoffe in erwärmtem Zustand');
COMMIT;
